const products = [
    {
        _id: 1,
        name: 'A',
        image: '/images/airpods.jpg',
        description: 'Hehe',
        brand: 'Apple',
        category: 'Electronics',
        prices: 88,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 2,
        name: 'B',
        image: '/images/alexa.jpg',
        description: 'Hehe',
        brand: 'Apple',
        category: 'Electronics',
        prices: 882,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 3,
        name: 'C',
        image: '/images/camera.jpg',
        description: 'Hehe',
        brand: 'Apple',
        category: 'Electronics',
        prices: 828,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 4,
        name: 'D',
        image: '/images/mouse.jpg',
        description: 'Hehe',
        brand: 'Apple',
        category: 'Electronics',
        prices: 848,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
    {
        _id: 5,
        name: 'E',
        image: '/images/phone.jpg',
        description: 'Hehe',
        brand: 'Apple',
        category: 'Electronics',
        prices: 388,
        countInStock: 3,
        rating: 2,
        numReviews: 4,
    },
    {
        _id: 6,
        name: 'F',
        image: '/images/playstation.jpg',
        description: 'Hehe',
        brand: 'Apple',
        category: 'Electronics',
        prices: 8855,
        countInStock: 3,
        rating: 5,
        numReviews: 4,
    }
]

export default products